services:
  - type: web
    name: eqlog-http
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB
        value: eqlog
      - key: SESSION_SECRET
        generateValue: true
      - key: COOKIE_SECURE
        value: "false"
